name: Borneo-drought
channels:
  - conda-forge
dependencies:
  - python=3.8
  - jupyter
  - ipywidgets
  - ipykernel
  - pandas
  - xarray
  - xclim
  - cartopy
  - bokeh
  - scikit-learn
  - jupyterlab
  - dask
  - netCDF4
  - bottleneck
  - iris
